version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: docker/dev.Dockerfile
    command: 'yarn serve:all'
    depends_on:
      - mongo
    environment:
      NODE_ENV: dev
      PORT: ${PORT:-3333}
      TESCO_URL: ${TESCO_URL}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-36}
      VCR_MODE: ${VCR_MODE:-}
      RUN_MIGRATION: ${RUN_MIGRATION:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
    ports:
      - ${PORT:-3333}:${PORT:-3333}
      - 4200:4200
    networks:
      webnet:
      mongo_network:
    volumes:
      - ./apps:/usr/src/app/apps
      - ./config:/usr/src/app/config
      - ./libs:/usr/src/app/libs
      - ./tools:/usr/src/app/tools
      - ./node_modules:/usr/src/app/node_modules
      - ./angular.json:/usr/src/app/angular.json:ro
      - ./decorate-angular-cli.js:/usr/src/app/decorate-angular-cli.js:ro
      - ./jest.preset.js:/usr/src/app/jest.preset.js:ro
      - ./nx.json:/usr/src/app/nx.json:ro
      #- ./nest-cli.json:/usr/src/app/nest-cli.json:ro
      - ./tsconfig.base.json:/usr/src/app/tsconfig.base.json:ro
      - ./package.json:/usr/src/app/package.json:ro
      - ./yarn.lock:/usr/src/app/yarn.lock:ro
      - ./.cache:/tmp/cache
      - ./.cache/fixtures:/usr/src/app/fixtures
    restart: on-failure
  mongo:
    image: mongo:5
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      - 27017:27017
    networks:
      mongo_network:

networks:
  webnet:
    external: true
  mongo_network:
