service:
  name: supermarket-watch

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 128
  timeout: 30

functions:
  getProduct:
    handler: index.getProduct
    events:
      - http:
          method: get
          path: getProduct
  search:
    handler: index.search
    events:
      - http:
          method: get
          path: search
