service:
  name: supermarket-watch

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2
  memorySize: 128

functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          method: get
          path: getProduct
