version: '3.8'

services:
  api:
    container_name: shopping-api
    image: ghcr.io/paullessing/supermarket-watch:latest
    depends_on:
      - mongo
      - proxy
    command: yarn start:api
    ports:
      - ${PORT:-3333}:3333
    environment:
      # Config for the application
      NODE_ENV: prod
      PORT: ${PORT:-3333}
      TESCO_API_KEY: ${TESCO_API_KEY:?Tesco API Key is required}
      TESCO_URL: ${TESCO_URL}
      SAINSBURYS_URL: ${SAINSBURYS_URL}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-36}
    restart: always
    networks:
      webnet:
      supermarket_network:
  proxy:
    container_name: shopping-proxy
    image: ghcr.io/paullessing/supermarket-watch-proxy:latest
    expose:
      - ${PORT:-3333}
    restart: always
    networks:
      supermarket_network:
  mongo:
    container_name: shopping-db
    image: mongo:5
    restart: always
    networks:
      supermarket_network:
    volumes:
      - mongodata:/data/db
    # restart_policy is not supported outside docker swarm, despite v3 docs saying it should be used
    # restart_policy:
    #   condition: any

networks:
  webnet:
    external: true
  supermarket_network:

volumes:
  mongodata:
