version: '3'

services:
  api:
    container_name: shoppi_lessi_ng
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: yarn start:api
    ports:
      - ${HOST_PORT:-3333}:${PORT:-3333}
    environment:
      # Config for the application
      NODE_ENV: prod
      PORT: ${PORT:-3333}
      TESCO_API_KEY: ${TESCO_API_KEY:?Tesco API Key is required}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-36}
    networks:
      webnet:
#    restart_policy: on-failure
    restart: unless-stopped

networks:
  webnet:
    external: true
