version: '3'

services:
  api:
    build: .
    command: yarn serve:dev
    ports:
      - 3000:3000
      - 4200:4200
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/frontend/node_modules
      - ./dist/:/usr/src/app
      - ./config/config.json:/usr/src/app/config.json
    environment:
      NODE_ENV: development
