version: '3'

services:
  api:
    image: node:12
    working_dir: /usr/src/app
    command: sh -c 'yarn --cache-folder /tmp/yarn-cache && yarn serve:all'
    ports:
      - 3333:3333
      - 4200:4200
    environment:
      # Config for the application
      NODE_ENV: development
      PORT: ${PORT:-3333}
      TESCO_API_KEY: ${TESCO_API_KEY:-0000000000000000000000000}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-120}
    volumes:
      - ../package.json:/usr/src/app/package.json
      - ../yarn.lock:/usr/src/app/yarn.lock
      - ../tsconfig.json:/usr/src/app/tsconfig.json
      - ../nx.json:/usr/src/app/nx.json
      - ../angular.json:/usr/src/app/angular.json
      - ../apps:/usr/src/app/apps
      - ../libs:/usr/src/app/libs
      - ../tools:/usr/src/app/tools
      - /tmp/yarn-cache
    networks:
      webnet:
#    restart_policy: on-failure

networks:
  webnet:
    external: true
