version: '3'

services:
  api:
    container_name: shoppi_lessi_ng
    image: ghcr.io/paullessing/supermarket-watch:latest
    command: sh -c "ip route add 192.168.255.0/24 via 172.30.0.100 && yarn start:api" # Allow the proxy through
    cap_add: # Required to make `ip route add` work
      - NET_ADMIN
    expose:
      - ${PORT:-3333}
    environment:
      # Config for the application
      NODE_ENV: prod
      PORT: ${PORT:-3333}
      TESCO_API_KEY: ${TESCO_API_KEY:?Tesco API Key is required}
      TESCO_PRODUCT_URL: ${TESCO_PRODUCT_URL}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-36}
      DB_DIR_PATH: ${DB_DIR_PATH}

      # Nginx Config
      VIRTUAL_PORT: ${PORT:-3333}
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
    networks:
      webnet:
    #    restart_policy: on-failure
    volumes:
      - db:/db

volumes:
  db:

networks:
  webnet:
    external: true
