version: '3'

services:
  api:
    container_name: shoppi_lessi_ng
    image: ghcr.io/paullessing/supermarket-watch:latest
    ports:
      - ${HOST_PORT:-3333}:${PORT:-3333}
    environment:
      # Config for the application
      NODE_ENV: prod
      PORT: ${PORT:-3333}
      TESCO_API_KEY: ${TESCO_API_KEY:?Tesco API Key is required}
      SEARCH_RESULT_COUNT: ${SEARCH_RESULT_COUNT:-36}
      # Nginx Config
      VIRTUAL_PORT: ${PORT:-3333}
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
    networks:
      webnet:
#    restart_policy: on-failure

networks:
  webnet:
    external: true
