name: Build Docker Image

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  release:
#    types: [published]

jobs:
  push_to_registry:
    name: "Build and Push Docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: "./docker/Dockerfile"
          push: true
          tags: "ghcr.io/paullessing/supermarket-watch:latest,ghcr.io/paullessing/supermarket-watch:${{ github.sha }}"
