name: Build Docker Image

on:
  # Triggers the workflow on push to main
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  release:
#    types: [published]

jobs:
  push_to_registry:
    name: 'Build and Push Docker image'
    runs-on: ubuntu-latest
    steps:
      # Steps not needed if not building for ARM
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v1
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1
      - name: Login to Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          file: './docker/Dockerfile'
          push: true
          tags: 'ghcr.io/paullessing/supermarket-watch:latest,ghcr.io/paullessing/supermarket-watch:${{ github.sha }}'
