name: Build Docker Image

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'
      - run: npm ci
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
      - run: yarn affected:build
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run test
  push_to_registry:
    name: Build and Push Docker image
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    needs: [ build, lint, test ]
    steps:
      # Steps not needed if not building for ARM
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v1
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1
      - name: Login to Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          file: './docker/Dockerfile'
          push: true
          tags: 'ghcr.io/paullessing/supermarket-watch:${{ github.sha }}'
      - name: Build and Push Proxy to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          file: './docker/proxy.Dockerfile'
          push: true
          tags: 'ghcr.io/paullessing/supermarket-watch-proxy:${{ github.sha }}'
# See also https://nx.dev/ci/monorepo-ci-github-actions
